### PR TITLE
Update command options

### PR DESCRIPTION
**Pull request by okonomi**
Update `pagekit` command options in PageKit 1.0.3.

### CODE REVIEW

**Comment by florianletsch** [comment]
Thanks for the PR.

Why have you renamed the arguments in the docs? Will you also create a PR for the renamed arguments in the actual code, or is this just a suggestion? https://github.com/pagekit/docs/pull/76/commits/331f771c810d861c938a617a5cf5b5e097061819#diff-5a83a14993007fc84341241b4b34dc4cL214

**Comment by okonomi** [comment]
@florianletsch No, I just updated document in accordance with latest `pagekit` command.
It was followed the commit log, It has been changed options of setup command in this commit.

https://github.com/pagekit/pagekit/commit/8255cd359f5e62c0bfc0436b634d38a2708befe4#diff-15da155a0882f3fe96090c0bdf9d66e3L31

**Comment by florianletsch** [comment]
Oh, you're right. Thanks!

**Comment by okonomi** [comment]
Thanks for marging. 😃

**Pull request merged**
